import assert from "node:assert/strict";
import test from "node:test";
import { importCompiled } from "./esbuild-import.mjs";

const catalog = await importCompiled("app/catalog.tsx");
const series = await importCompiled("app/series.ts");
const { parseSpec, itemMM, byStone, byAccessory, capacityForWrist, strandArcMM } = catalog;
const { SERIES } = series;

// series.ts is generated by scripts/gen-series.py, which is supposed to
// guarantee every product it emits fits its own wrist size and clears the
// studio's 80% checkout gate (page.tsx:316) — but nothing enforces that once
// a product is hand-edited afterward. Pin the guarantee here instead of only
// at generation time.
const CHECKOUT_FILL_GATE = 0.8;

test("every series has a non-empty id/zh/en/products, no duplicate series ids", () => {
  assert.ok(SERIES.length > 0);
  const ids = new Set();
  for (const s of SERIES) {
    assert.ok(s.id && s.zh && s.en, `series ${s.id} missing id/zh/en`);
    assert.ok(s.products.length > 0, `series ${s.id} has no products`);
    assert.ok(!ids.has(s.id), `duplicate series id ${s.id}`);
    ids.add(s.id);
  }
});

test("every product spec references only real stone/accessory ids", () => {
  for (const s of SERIES) {
    for (const p of s.products) {
      for (const token of p.spec.split(",")) {
        const [id] = token.trim().split(".");
        assert.ok(byStone[id] || byAccessory[id], `${s.id}/${p.id}: unknown catalogue id "${id}" in spec`);
      }
    }
  }
});

test("every product fits its own wrist size", () => {
  for (const s of SERIES) {
    for (const p of s.products) {
      const widths = parseSpec(p.spec).map(itemMM);
      // 珠心圈由手圍外推（見 strand-geometry），不是手圍本身
      const cap = capacityForWrist(p.wrist, widths);
      const used = strandArcMM(widths, cap);
      assert.ok(used <= cap, `${s.id}/${p.id}: ${used.toFixed(0)}mm strand exceeds ${cap.toFixed(0)}mm (wrist ${p.wrist}cm)`);
    }
  }
});

test("every product clears the 80% checkout fill gate", () => {
  for (const s of SERIES) {
    for (const p of s.products) {
      const widths = parseSpec(p.spec).map(itemMM);
      const cap = capacityForWrist(p.wrist, widths);
      const fillRatio = strandArcMM(widths, cap) / cap;
      assert.ok(fillRatio >= CHECKOUT_FILL_GATE, `${s.id}/${p.id}: fill ratio ${fillRatio.toFixed(2)} is below the ${CHECKOUT_FILL_GATE} checkout gate`);
    }
  }
});

test("no duplicate product ids within a series", () => {
  for (const s of SERIES) {
    const ids = new Set(s.products.map((p) => p.id));
    assert.equal(ids.size, s.products.length, `${s.id}: duplicate product id`);
  }
});
