-- Material expansion: the full sundayfate-equivalent breadth, priced in
-- TWD (USD x31.5 rounded to NT$5) via the 價格對照表. Every row ships
-- with photo='' — hidden from the storefront until the admin uploads a
-- photo, so the catalog grows one finished material at a time.
-- Energy weights start from a per-dominant-energy template; fine-tune in
-- the admin's weight editor.
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('fire-quartz', '血膽赤晶', 'Fire Quartz', '力量', 110, '', '{"wealth": 4, "love": 3, "healing": 4, "protection": 5, "focus": 5, "power": 9}', '', 101, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('fire-quartz', 10, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('fire-quartz', 12, 45, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('hematoid-quartz-cube', '血膽水晶方糖', 'Hematoid Quartz Cube', '力量', 65, '', '{"wealth": 4, "love": 3, "healing": 4, "protection": 5, "focus": 5, "power": 9}', '', 102, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('hematoid-quartz-cube', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('red-agate', '紅瑪瑙', 'Red Agate', '力量', 30, '', '{"wealth": 4, "love": 3, "healing": 4, "protection": 5, "focus": 5, "power": 9}', '', 103, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('red-agate', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('red-agate', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('red-agate', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('red-hair-quartz', '紅兔毛晶', 'Red Hair Quartz', '力量', 80, '', '{"wealth": 4, "love": 3, "healing": 4, "protection": 5, "focus": 5, "power": 9}', '', 104, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('red-hair-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('red-hair-quartz', 10, 45, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('red-hair-quartz', 12, 95, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('amethyst-cube', '紫水晶方糖', 'Amethyst Cube', '守護', 65, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 105, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amethyst-cube', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('amethyst-dt', '紫水晶雙尖柱', 'Amethyst DT', '守護', 65, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 106, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amethyst-dt', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('amethyst-heart', '紫水晶愛心', 'Amethyst Heart', '守護', 65, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 107, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amethyst-heart', 17, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('amethyst-running-ring', '紫水晶跑環', 'Amethyst Running Ring', '守護', 125, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 108, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amethyst-running-ring', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('amethyst-star', '紫水晶星星', 'Amethyst Star', '守護', 65, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 109, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amethyst-star', 15, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('black-obsidian', '黑曜石', 'Black Obsidian', '守護', 15, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 110, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-obsidian', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-obsidian', 10, 5, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-obsidian', 12, 15, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('blue-tiger-eye', '藍虎眼石', 'Blue tiger eye', '守護', 65, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 111, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-tiger-eye', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-tiger-eye', 10, 45, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-tiger-eye', 12, 75, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('brazilian-amethyst', '巴西紫水晶', 'Brazilian Amethyst', '守護', 95, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 112, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('brazilian-amethyst', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('brazilian-amethyst', 10, 95, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('brazilian-amethyst', 12, 170, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('carved-amethyst-fox', '紫水晶雕刻狐狸', 'Carved Amethyst Fox', '守護', 125, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 113, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('carved-amethyst-fox', 15, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('faceted-amethyst', '切面紫水晶', 'Faceted Amethyst', '守護', 30, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 114, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('faceted-amethyst', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('golden-obsidian', '金曜石', 'Golden Obsidian', '守護', 30, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 115, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-obsidian', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-obsidian', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-obsidian', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('hetian-jade', '和田玉', 'Hetian Jade', '守護', 80, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 116, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('hetian-jade', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('hetian-jade', 10, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('hetian-jade', 12, 60, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('ice-obsidian', '冰曜石', 'Ice Obsidian', '守護', 30, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 117, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('ice-obsidian', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('ice-obsidian', 10, 10, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('ice-obsidian', 12, 15, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('lavender-amethyst', '薰衣草紫水晶', 'Lavender Amethyst', '守護', 65, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 118, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lavender-amethyst', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lavender-amethyst', 10, 30, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('malachite', '孔雀石', 'Malachite', '守護', 15, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 119, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('malachite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('malachite', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('malachite', 12, 30, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('silver-obsidian', '銀曜石', 'Silver Obsidian', '守護', 30, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 120, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('silver-obsidian', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('silver-obsidian', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('silver-obsidian', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('uruguayan-amethyst', '烏拉圭紫水晶', 'Uruguayan Amethyst', '守護', 15, '', '{"wealth": 3, "love": 3, "healing": 5, "protection": 9, "focus": 5, "power": 6}', '', 121, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('uruguayan-amethyst', 4, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('uruguayan-amethyst', 6, 10, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('uruguayan-amethyst', 8, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('uruguayan-amethyst', 10, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('uruguayan-amethyst', 12, 50, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('uruguayan-amethyst', 14, 65, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('clear-quartz-cube', '白水晶方糖', 'Clear Quartz Cube', '專注', 65, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 122, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('clear-quartz-cube', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('clear-quartz-dt', '白水晶雙尖柱', 'Clear Quartz DT', '專注', 65, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 123, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('clear-quartz-dt', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('clear-quartz-faceted-cube', '白水晶切角方糖', 'Clear Quartz Faceted Cube', '專注', 65, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 124, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('clear-quartz-faceted-cube', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('clear-quartz-heart', '白水晶愛心', 'Clear Quartz Heart', '專注', 65, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 125, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('clear-quartz-heart', 17, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('clear-quartz-pill-bead', '白水晶藥丸珠', 'Clear Quartz Pill Bead', '專注', 65, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 126, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('clear-quartz-pill-bead', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('feather-fluorite', '羽毛螢石', 'Feather Fluorite', '專注', 65, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 127, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('feather-fluorite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('feather-fluorite', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('feather-fluorite', 12, 30, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('green-fluorite', '綠螢石', 'Green Fluorite', '專注', 30, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 128, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-fluorite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-fluorite', 10, 35, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-fluorite', 12, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('kyanite', '藍晶石', 'Kyanite', '專注', 45, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 129, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('kyanite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('kyanite', 10, 50, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('kyanite', 12, 65, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('milky-quartz', '乳白水晶', 'Milky Quartz', '專注', 45, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 130, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('milky-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('milky-quartz', 10, 20, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('milky-quartz', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('white-aze-crystal', '白阿賽晶', 'White Aze Crystal', '專注', 30, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 131, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-aze-crystal', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-aze-crystal', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-aze-crystal', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('white-cat-eye', '白貓眼石', 'White Cat Eye', '專注', 15, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 132, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-cat-eye', 4, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-cat-eye', 6, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-cat-eye', 8, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-cat-eye', 10, 40, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-cat-eye', 12, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('white-crystal-running-hoop', '白水晶跑環', 'White Crystal Running Hoop', '專注', 80, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 133, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-crystal-running-hoop', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('yellow-fluorite', '黃螢石', 'Yellow Fluorite', '專注', 30, '', '{"wealth": 4, "love": 3, "healing": 5, "protection": 5, "focus": 9, "power": 5}', '', 134, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-fluorite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-fluorite', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-fluorite', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('baroque-pearl', '巴洛克珍珠', 'Baroque Pearl', '愛情', 15, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 135, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('baroque-pearl', 4, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('champagne-pink-rice-pearl', '香檳粉米粒珍珠', 'Champagne Pink Rice Pearl', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 136, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('champagne-pink-rice-pearl', 6, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('champagne-pink-threaded-pearl', '香檳粉螺紋珍珠', 'Champagne Pink Threaded Pearl', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 137, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('champagne-pink-threaded-pearl', 9, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('cherry-blossom-rhodonite', '櫻花薔薇輝石', 'Cherry Blossom Rhodonite', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 138, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('cherry-blossom-rhodonite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('cherry-blossom-rhodonite', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('cherry-blossom-rhodonite', 12, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('dusty-rose-strawberry-quartz', '灰玫草莓晶', 'Dusty Rose Strawberry Quartz', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 139, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('dusty-rose-strawberry-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('dusty-rose-strawberry-quartz', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('dusty-rose-strawberry-quartz', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('faceted-sakura-agate', '切面櫻花瑪瑙', 'Faceted Sakura Agate', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 140, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('faceted-sakura-agate', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('faceted-sakura-agate', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('faceted-sakura-agate', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('kunzite', '紫鋰輝石', 'Kunzite', '愛情', 15, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 141, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('kunzite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('kunzite', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('kunzite', 12, 30, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('lavender-rose-quartz', '薰衣草粉晶', 'Lavender Rose Quartz', '愛情', 45, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 142, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lavender-rose-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lavender-rose-quartz', 10, 20, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lavender-rose-quartz', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('lavender-threaded-pearl', '薰衣草螺紋珍珠', 'Lavender Threaded Pearl', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 143, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lavender-threaded-pearl', 9, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('madagascar-rose-quartz', '馬達加斯加粉晶', 'Madagascar Rose Quartz', '愛情', 15, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 144, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('madagascar-rose-quartz', 4, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('madagascar-rose-quartz', 6, 10, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('madagascar-rose-quartz', 8, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('madagascar-rose-quartz', 10, 25, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('madagascar-rose-quartz', 12, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('madagascar-rose-quartz', 14, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('pigeon-blood-strawberry-quartz', '鴿血紅草莓晶', 'Pigeon Blood Strawberry Quartz', '愛情', 45, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 145, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('pigeon-blood-strawberry-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('pigeon-blood-strawberry-quartz', 10, 35, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('pigeon-blood-strawberry-quartz', 12, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('rhodochrosite', '紅紋石（菱錳礦）', 'Rhodochrosite', '愛情', 95, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 146, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('rhodochrosite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('rhodochrosite', 10, 60, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('rhodochrosite', 12, 155, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('rose-quartz-dt', '粉晶雙尖柱', 'Rose Quartz DT', '愛情', 65, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 147, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('rose-quartz-dt', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('rose-quartz-heart', '粉晶愛心', 'Rose Quartz Heart', '愛情', 65, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 148, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('rose-quartz-heart', 17, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('rose-quartz-star', '粉晶星星', 'Rose Quartz Star', '愛情', 65, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 149, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('rose-quartz-star', 15, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('round-pearl', '圓珍珠', 'Round Pearl', '愛情', 15, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 150, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('round-pearl', 2, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('round-pearl', 4, 5, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('round-pearl', 6, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('round-pearl', 8, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('star-rose-quartz', '星光粉晶', 'Star Rose Quartz', '愛情', 65, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 151, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('star-rose-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('star-rose-quartz', 10, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('star-rose-quartz', 12, 75, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('vintage-rose-rhodonite', '復古玫瑰薔薇輝石', 'Vintage Rose Rhodonite', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 152, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('vintage-rose-rhodonite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('vintage-rose-rhodonite', 10, 35, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('vintage-rose-rhodonite', 12, 65, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('white-rice-pearl', '白米粒珍珠', 'White Rice Pearl', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 153, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-rice-pearl', 6, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('white-threaded-pearl', '白螺紋珍珠', 'White Threaded Pearl', '愛情', 30, '', '{"wealth": 3, "love": 9, "healing": 7, "protection": 4, "focus": 4, "power": 4}', '', 154, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('white-threaded-pearl', 9, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('amazonite', '天河石', 'Amazonite', '療癒', 30, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 155, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amazonite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amazonite', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('amazonite', 12, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('black-star-aquamarine', '黑星海藍寶', 'Black Star Aquamarine', '療癒', 125, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 156, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-star-aquamarine', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-star-aquamarine', 10, 160, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-star-aquamarine', 12, 285, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('blue-lace-agate', '藍紋瑪瑙', 'Blue Lace Agate', '療癒', 30, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 157, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-lace-agate', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-lace-agate', 10, 35, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-lace-agate', 12, 65, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('blue-sheen', '藍光月光石', 'Blue Sheen', '療癒', 65, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 158, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-sheen', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-sheen', 10, 60, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('blue-sheen', 12, 125, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('creamy-aquamarine', '奶油海藍寶', 'Creamy Aquamarine', '療癒', 15, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 159, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('creamy-aquamarine', 4, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('creamy-aquamarine', 6, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('creamy-aquamarine', 8, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('creamy-aquamarine', 10, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('dark-blue-aquamarine', '深藍海藍寶', 'Dark Blue Aquamarine', '療癒', 80, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 160, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('dark-blue-aquamarine', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('dark-blue-aquamarine', 10, 75, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('dark-blue-aquamarine', 12, 140, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('devil-blue-aquamarine', '魔鬼藍海藍寶', 'Devil Blue Aquamarine', '療癒', 95, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 161, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('devil-blue-aquamarine', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('devil-blue-aquamarine', 10, 95, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('devil-blue-aquamarine', 12, 220, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('garden-quartz-dt', '庭園水晶雙尖柱', 'Garden Quartz DT', '療癒', 65, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 162, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('garden-quartz-dt', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('golden-healer-quartz', '金療癒水晶', 'Golden Healer Quartz', '療癒', 95, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 163, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-healer-quartz', 10, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-healer-quartz', 12, 45, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('golden-prehnite', '金葡萄石', 'Golden Prehnite', '療癒', 65, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 164, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-prehnite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-prehnite', 10, 45, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-prehnite', 12, 75, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('green-agate', '綠瑪瑙', 'Green Agate', '療癒', 15, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 165, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-agate', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-agate', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-agate', 12, 30, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('green-grape-xiuyan-jade', '綠葡萄岫岩玉', 'Green Grape Xiuyan Jade', '療癒', 30, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 166, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-grape-xiuyan-jade', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-grape-xiuyan-jade', 10, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-grape-xiuyan-jade', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('green-prehnite', '綠葡萄石', 'Green Prehnite', '療癒', 45, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 167, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-prehnite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-prehnite', 10, 35, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-prehnite', 12, 80, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('grey-moonstone', '灰月光石', 'Grey Moonstone', '療癒', 65, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 168, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('grey-moonstone', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('grey-moonstone', 10, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('grey-moonstone', 12, 90, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('ice-blue-aquamarine', '冰藍海藍寶', 'Ice Blue Aquamarine', '療癒', 65, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 169, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('ice-blue-aquamarine', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('ice-blue-aquamarine', 10, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('ice-blue-aquamarine', 12, 90, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('larimar', '拉利瑪', 'Larimar', '療癒', 190, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 170, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('larimar', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('larimar', 10, 190, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('larimar', 12, 375, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('milky-moonstone', '奶白月光石', 'Milky Moonstone', '療癒', 30, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 171, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('milky-moonstone', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('milky-moonstone', 10, 35, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('milky-moonstone', 12, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('prehnite-cabochon', '葡萄石蛋面', 'Prehnite Cabochon', '療癒', 95, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 172, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('prehnite-cabochon', 12, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('seraphinite', '綠龍晶', 'Seraphinite', '療癒', 45, '', '{"wealth": 3, "love": 6, "healing": 9, "protection": 5, "focus": 5, "power": 4}', '', 173, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('seraphinite', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('seraphinite', 10, 20, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('seraphinite', 12, 35, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('black-gold-super-seven', '黑金超七', 'Black Gold Super Seven', '財富', 65, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 174, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-gold-super-seven', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-gold-super-seven', 10, 60, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-gold-super-seven', 12, 110, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('black-rutilated-quartz', '黑髮晶', 'Black Rutilated Quartz', '財富', 95, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 175, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-rutilated-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-rutilated-quartz', 10, 45, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('black-rutilated-quartz', 12, 140, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('brazilian-citrine', '巴西黃水晶', 'Brazilian Citrine', '財富', 155, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 176, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('brazilian-citrine', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('brazilian-citrine', 10, 160, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('citrine-cube', '黃水晶方糖', 'Citrine Cube', '財富', 65, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 177, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('citrine-cube', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('citrine-dt', '黃水晶雙尖柱', 'Citrine DT', '財富', 65, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 178, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('citrine-dt', 10, 0, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('golden-rutilated-quartz', '金髮晶（鈦晶）', 'Golden Rutilated Quartz', '財富', 95, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 179, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-rutilated-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-rutilated-quartz', 10, 95, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-rutilated-quartz', 12, 190, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('golden-tower-citrine', '金塔黃水晶', 'Golden Tower Citrine', '財富', 15, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 180, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tower-citrine', 4, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tower-citrine', 6, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tower-citrine', 8, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tower-citrine', 10, 65, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tower-citrine', 12, 80, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('golden-tiger-eye', '金虎眼石', 'Golden tiger eye', '財富', 45, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 181, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tiger-eye', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tiger-eye', 10, 50, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('golden-tiger-eye', 12, 80, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('green-hair-quartz', '綠兔毛晶', 'Green Hair Quartz', '財富', 80, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 182, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-hair-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-hair-quartz', 10, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-hair-quartz', 12, 75, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('green-phantom-crystal', '綠幽靈', 'Green Phantom Crystal', '財富', 30, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 183, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-phantom-crystal', 6, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-phantom-crystal', 8, 35, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-phantom-crystal', 10, 65, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-phantom-crystal', 12, 110, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('green-rutilated-quartz', '綠髮晶', 'Green Rutilated Quartz', '財富', 65, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 184, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-rutilated-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-rutilated-quartz', 10, 45, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('green-rutilated-quartz', 12, 110, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('lemon-quartz', '檸檬晶', 'Lemon Quartz', '財富', 45, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 185, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lemon-quartz', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lemon-quartz', 10, 20, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('lemon-quartz', 12, 50, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('purple-phantom-crystal', '紫幽靈', 'Purple Phantom Crystal', '財富', 65, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 186, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('purple-phantom-crystal', 10, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('purple-phantom-crystal', 12, 30, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('snowflake-phantom', '雪花幽靈', 'Snowflake Phantom', '財富', 65, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 187, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('snowflake-phantom', 8, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('snowflake-phantom', 10, 30, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('snowflake-phantom', 12, 75, 0, 1);
INSERT OR IGNORE INTO stones (id, zh, en, energy_zh, price, note, energies, photo, sort, active) VALUES ('yellow-tiger-eye', '黃虎眼石', 'Yellow tiger eye', '財富', 15, '', '{"wealth": 9, "love": 3, "healing": 4, "protection": 5, "focus": 6, "power": 7}', '', 188, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-tiger-eye', 4, 0, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-tiger-eye', 6, 5, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-tiger-eye', 8, 15, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-tiger-eye', 10, 50, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-tiger-eye', 12, 80, 0, 1);
INSERT OR IGNORE INTO stone_sizes (stone_id, mm, price_delta, stock, active) VALUES ('yellow-tiger-eye', 14, 110, 0, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('wave-lace-spacer', '波浪蕾絲隔珠', 'Wave Lace Spacer', 'spacer', 'silver', 30, '', '', 0, 101, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('guardian-x-spacer', '守護X隔珠', 'Guardian X Spacer', 'spacer', 'silver', 30, '', '', 0, 102, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('rose-gold-crystal-rondelle-spacer', '玫瑰金方鑽隔珠', 'Rose Gold Crystal Rondelle Spacer', 'spacer', 'gold', 30, '', '', 0, 103, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('lace-crown-spacer', '蕾絲皇冠隔珠', 'Lace Crown Spacer', 'spacer', 'silver', 30, '', '', 0, 104, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('roman-dial-spacer', '羅馬錶盤隔珠', 'Roman Dial Spacer', 'spacer', 'silver', 30, '', '', 0, 105, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-tone-mystic-mask-spacer', '銀色神秘面具隔珠', 'Silver-Tone Mystic Mask Spacer', 'spacer', 'silver', 30, '', '', 0, 106, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('openwork-geometric-bead', '鏤空幾何珠', 'Openwork Geometric Bead', 'spacer', 'silver', 30, '', '', 0, 107, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('honeycomb-bead', '蜂巢珠', 'Honeycomb Bead', 'spacer', 'silver', 30, '', '', 0, 108, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('polished-rose-spark-spacer-silver-tone', '銀色玫瑰光隔珠', 'Polished Rose Spark Spacer Silver-Tone', 'spacer', 'silver', 30, '', '', 0, 109, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('vintage-coin-tube-spacer-silver-tone', '銀色復古錢幣管珠', 'Vintage Coin Tube Spacer Silver-Tone', 'spacer', 'silver', 30, '', '', 0, 110, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('twisted-tube-spacer-silver-tone', '銀色麻花管珠', 'Twisted Tube Spacer Silver-Tone', 'spacer', 'silver', 30, '', '', 0, 111, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('vintage-tribal-tiki-spacer', '復古圖騰隔珠', 'Vintage Tribal Tiki Spacer', 'spacer', 'silver', 30, '', '', 0, 112, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('matte-donut-spacer-gold-tone', '金色消光甜甜圈隔珠', 'Matte Donut Spacer Gold-Tone', 'spacer', 'gold', 10, '', '', 0, 113, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('satin-gold-wisdom-eye', '緞金智慧眼隔珠', 'Satin Gold Wisdom Eye', 'spacer', 'gold', 10, '', '', 0, 114, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('reversible-floral-cape', '雙面花斗篷隔珠', 'Reversible Floral Cape', 'spacer', 'silver', 30, '', '', 0, 115, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('zircon-wheel-spacer', '鋯石輪隔珠', 'Zircon wheel Spacer', 'spacer', 'silver', 15, '', '', 0, 116, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gothic-cross', '哥德十字隔珠', 'Gothic Cross', 'spacer', 'silver', 5, '', '', 0, 117, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gold-small-bead', '金色小圓珠', 'Gold small bead', 'spacer', 'gold', 5, '', '', 0, 118, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-small-bead', '銀色小圓珠', 'Silver small bead', 'spacer', 'silver', 5, '', '', 0, 119, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('aquamarine-box-spacer', '海藍寶方牌隔珠', 'Aquamarine Box Spacer', 'spacer', 'silver', 125, '', '', 0, 120, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('aquamarine-fortune-wheel-box-spacer', '海藍寶轉運輪方牌', 'Aquamarine Fortune Wheel Box Spacer', 'spacer', 'silver', 80, '', '', 0, 121, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('rose-quartz-box-spacer', '粉晶方牌隔珠', 'Rose Quartz Box Spacer', 'spacer', 'silver', 95, '', '', 0, 122, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('phantom-quartz-box-spacer', '幽靈方牌隔珠', 'Phantom Quartz Box Spacer', 'spacer', 'silver', 95, '', '', 0, 123, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('blue-moonstone-box-spacer', '藍月光方牌隔珠', 'Blue Moonstone Box Spacer', 'spacer', 'silver', 95, '', '', 0, 124, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('rose-quartz-bloom-box-spacer', '粉晶花開方牌', 'Rose Quartz Bloom Box Spacer', 'spacer', 'silver', 95, '', '', 0, 125, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('blue-moonstone-fortune-wheel-box-spacer', '藍月光轉運輪方牌', 'Blue Moonstone Fortune Wheel Box Spacer', 'spacer', 'silver', 95, '', '', 0, 126, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('amethyst-bloom-box-spacer', '紫晶花開方牌', 'Amethyst Bloom Box Spacer', 'spacer', 'silver', 80, '', '', 0, 127, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('heart-cut-crystal', '心形切割水晶隔珠', 'Heart-Cut Crystal', 'spacer', 'silver', 30, '', '', 0, 128, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('stacked-band', '疊環隔珠', 'Stacked Band', 'spacer', 'silver', 30, '', '', 0, 129, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('floral-silver-disc', '銀花圓片隔珠', 'Floral Silver Disc', 'spacer', 'silver', 30, '', '', 0, 130, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('matte-filigree-orb', '消光雕花圓珠', 'Matte Filigree Orb', 'spacer', 'silver', 15, '', '', 0, 131, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('filigree-clover', '雕花幸運草隔珠', 'Filigree Clover', 'spacer', 'silver', 30, '', '', 0, 132, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gunmetal-crown', '槍灰皇冠隔珠', 'Gunmetal Crown', 'spacer', 'silver', 30, '', '', 0, 133, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('onyx-spacer', '縞瑪瑙隔珠', 'Onyx Spacer', 'spacer', 'silver', 15, '', '', 0, 134, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gunmetal-cross', '槍灰十字隔珠', 'Gunmetal Cross', 'spacer', 'silver', 30, '', '', 0, 135, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('braided-spacer', '編織紋隔珠', 'Braided Spacer', 'spacer', 'silver', 20, '', '', 0, 136, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('fortune-bead', '轉運珠', 'Fortune Bead', 'spacer', 'silver', 30, '', '', 0, 137, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('wave-slice-gold-tone', '金色波浪片隔珠', 'Wave Slice Gold-Tone', 'spacer', 'gold', 15, '', '', 0, 138, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('melon-ribbed-bead', '瓜稜紋珠', 'Melon-Ribbed bead', 'spacer', 'silver', 15, '', '', 0, 139, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('circlet', '素圈隔珠', 'Circlet', 'spacer', 'silver', 15, '', '', 0, 140, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gunmetal-rippled-disc', '槍灰波紋圓片', 'Gunmetal Rippled Disc', 'spacer', 'silver', 15, '', '', 0, 141, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gunmetal-floral-spacer', '槍灰雕花隔珠', 'Gunmetal Floral Spacer', 'spacer', 'silver', 15, '', '', 0, 142, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gunmetal-rope-ring', '槍灰繩紋環', 'Gunmetal Rope Ring', 'spacer', 'silver', 15, '', '', 0, 143, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-double-sided-lotus', '銀雙面蓮花隔珠', 'Silver Double-Sided Lotus', 'spacer', 'silver', 15, '', '', 0, 144, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gilded-double-sided-lotus', '金雙面蓮花隔珠', 'Gilded Double-Sided Lotus', 'spacer', 'gold', 15, '', '', 0, 145, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('four-petal-floral-spacer', '四瓣花隔珠', 'Four-Petal Floral Spacer', 'spacer', 'silver', 20, '', '', 0, 146, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('sunburst-floral-spacer', '太陽花隔珠', 'Sunburst Floral Spacer', 'spacer', 'silver', 15, '', '', 0, 147, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('crown-cross', '皇冠十字隔珠', 'Crown Cross', 'spacer', 'silver', 20, '', '', 0, 148, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('eternity-knot-spacer', '永恆結隔珠', 'Eternity Knot Spacer', 'spacer', 'silver', 15, '', '', 0, 149, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('five-petal-bloom-spacer', '五瓣花隔珠', 'Five-Petal Bloom Spacer', 'spacer', 'silver', 15, '', '', 0, 150, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('hourglass-crystal', '沙漏水晶隔珠', 'Hourglass Crystal', 'spacer', 'silver', 30, '', '', 0, 151, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('spinner-sakura-crystal', '旋轉櫻花水晶', 'Spinner Sakura Crystal', 'spacer', 'silver', 95, '', '', 0, 152, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-floral-bow-spacer', '銀花蝴蝶結隔珠', 'Silver Floral Bow Spacer', 'spacer', 'silver', 15, '', '', 0, 153, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-disc', '銀圓片隔珠', 'Silver Disc', 'spacer', 'silver', 15, '', '', 0, 154, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-melon-ribbed-bead', '銀瓜稜紋珠', 'Silver Melon-Ribbed bead', 'spacer', 'silver', 15, '', '', 0, 155, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('sf-silver-star', '銀星星隔珠', 'Silver Star', 'spacer', 'silver', 30, '', '', 0, 156, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-lucky-star', '金幸運星吊飾', 'Golden Lucky Star', 'charm', 'gold', 65, '', '', 0, 157, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-lotus-chime-dangle', '金蓮花風鈴吊飾', 'Golden Lotus Chime Dangle', 'charm', 'gold', 65, '', '', 0, 158, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-moon-dangle', '金月亮吊飾', 'Golden Moon Dangle', 'charm', 'gold', 65, '', '', 0, 159, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-gourd-wealth-dangle', '金葫蘆招財吊飾', 'Golden Gourd Wealth Dangle', 'charm', 'gold', 65, '', '', 0, 160, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('triple-chime-dangle', '三鈴風鈴吊飾', 'Triple Chime Dangle', 'charm', 'silver', 65, '', '', 0, 161, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('mermaid-star-dangle', '人魚星吊飾', 'Mermaid Star Dangle', 'charm', 'silver', 65, '', '', 0, 162, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-butterfly-heart-dangle', '金蝶心吊飾', 'Golden Butterfly Heart Dangle', 'charm', 'gold', 65, '', '', 0, 163, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-angel-wing-cross-charm', '金天使翼十字吊飾', 'Golden Angel Wing Cross Charm', 'charm', 'gold', 65, '', '', 0, 164, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-butterfly-tulip-dangle', '金蝶鬱金香吊飾', 'Golden Butterfly Tulip Dangle', 'charm', 'gold', 65, '', '', 0, 165, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-gourd-logo-dangle', '金葫蘆牌吊飾', 'Golden Gourd & Logo Dangle', 'charm', 'gold', 65, '', '', 0, 166, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('golden-crystal-gourd-dangle', '金水晶葫蘆吊飾', 'Golden Crystal Gourd Dangle', 'charm', 'gold', 65, '', '', 0, 167, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('garnet-tulip-dangle', '石榴石鬱金香吊飾', 'Garnet Tulip Dangle', 'charm', 'silver', 65, '', '', 0, 168, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-butterfly-heart-dangle', '銀蝶心吊飾', 'Silver Butterfly Heart Dangle', 'charm', 'silver', 65, '', '', 0, 169, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('crystal-bloom-dangle', '水晶花開吊飾', 'Crystal Bloom Dangle', 'charm', 'silver', 65, '', '', 0, 170, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-lotus-chime-dangle', '銀蓮花風鈴吊飾', 'Silver Lotus Chime Dangle', 'charm', 'silver', 65, '', '', 0, 171, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-moon-dangle', '銀月亮吊飾', 'Silver Moon Dangle', 'charm', 'silver', 65, '', '', 0, 172, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-lucky-star', '銀幸運星吊飾', 'Silver Lucky Star', 'charm', 'silver', 65, '', '', 0, 173, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-gourd-logo-dangle', '銀葫蘆牌吊飾', 'Silver Gourd & Logo Dangle', 'charm', 'silver', 65, '', '', 0, 174, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-triple-chime-dangle', '銀三鈴風鈴吊飾', 'Silver Triple Chime Dangle', 'charm', 'silver', 65, '', '', 0, 175, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('abacus-wealth', '算盤招財吊飾', 'Abacus Wealth', 'charm', 'silver', 30, '', '', 0, 176, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('gunmetal-rose', '槍灰玫瑰吊飾', 'Gunmetal Rose', 'charm', 'silver', 65, '', '', 0, 177, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('starry-filigree-orb', '星空雕花球吊飾', 'Starry Filigree Orb', 'charm', 'silver', 30, '', '', 0, 178, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('dreamcatcher', '捕夢網吊飾', 'Dreamcatcher', 'charm', 'silver', 65, '', '', 0, 179, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('crystal-star', '水晶星星吊飾', 'Crystal Star', 'charm', 'silver', 30, '', '', 0, 180, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('dumpling-luck', '福氣餃子吊飾', 'Dumpling Luck', 'charm', 'silver', 65, '', '', 0, 181, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('kinetic-leaf-charm', '靈動葉片吊飾', 'Kinetic Leaf Charm', 'charm', 'silver', 30, '', '', 0, 182, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('pegasus', '飛馬吊飾', 'Pegasus', 'charm', 'silver', 65, '', '', 0, 183, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('pave-cross', '滿鑽十字吊飾', 'Pave Cross', 'charm', 'silver', 65, '', '', 0, 184, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('classic-cross', '經典十字吊飾', 'Classic Cross', 'charm', 'silver', 65, '', '', 0, 185, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('kitty', '小貓吊飾', 'Kitty', 'charm', 'silver', 65, '', '', 0, 186, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('crucifix', '受難十字吊飾', 'Crucifix', 'charm', 'silver', 65, '', '', 0, 187, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('lucky-cat', '招財貓吊飾', 'Lucky Cat', 'charm', 'silver', 30, '', '', 0, 188, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('sf-shell', '貝殼吊飾', 'Shell', 'charm', 'silver', 45, '', '', 0, 189, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('black-serpent', '黑蛇吊飾', 'Black Serpent', 'charm', 'silver', 45, '', '', 0, 190, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('butterfly-agate-orb', '蝶戀瑪瑙球吊飾', 'Butterfly & Agate Orb', 'charm', 'silver', 65, '', '', 0, 191, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('ancient-prosperity-coin', '古錢幣吊飾', 'Ancient Prosperity Coin', 'charm', 'silver', 15, '', '', 0, 192, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('north-star', '北極星吊飾', 'North Star', 'charm', 'silver', 45, '', '', 0, 193, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('fawn', '小鹿吊飾', 'Fawn', 'charm', 'silver', 15, '', '', 0, 194, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('man-in-the-moon', '月中人吊飾', 'Man in the Moon', 'charm', 'silver', 45, '', '', 0, 195, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('pink-evil-eye', '粉紅守護眼吊飾', 'Pink Evil Eye', 'charm', 'silver', 45, '', '', 0, 196, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('silver-snowflakes', '銀雪花吊飾', 'Silver snowflakes', 'charm', 'silver', 30, '', '', 0, 197, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('siren-s-tail', '人魚尾吊飾', 'Siren''s Tail', 'charm', 'silver', 15, '', '', 0, 198, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('intricate-weave-heart-charm', '織紋愛心吊飾', 'Intricate Weave Heart Charm', 'charm', 'silver', 45, '', '', 0, 199, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('cherub-angel-chram', '小天使吊飾', 'Cherub Angel chram', 'charm', 'silver', 45, '', '', 0, 200, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-a', '字母吊飾 A', 'Initial A', 'charm', 'gold', 65, '', '', 0, 201, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-b', '字母吊飾 B', 'Initial B', 'charm', 'gold', 65, '', '', 0, 202, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-c', '字母吊飾 C', 'Initial C', 'charm', 'gold', 65, '', '', 0, 203, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-d', '字母吊飾 D', 'Initial D', 'charm', 'gold', 65, '', '', 0, 204, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-e', '字母吊飾 E', 'Initial E', 'charm', 'gold', 65, '', '', 0, 205, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-f', '字母吊飾 F', 'Initial F', 'charm', 'gold', 65, '', '', 0, 206, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-g', '字母吊飾 G', 'Initial G', 'charm', 'gold', 65, '', '', 0, 207, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-h', '字母吊飾 H', 'Initial H', 'charm', 'gold', 65, '', '', 0, 208, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-i', '字母吊飾 I', 'Initial I', 'charm', 'gold', 65, '', '', 0, 209, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-j', '字母吊飾 J', 'Initial J', 'charm', 'gold', 65, '', '', 0, 210, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-k', '字母吊飾 K', 'Initial K', 'charm', 'gold', 65, '', '', 0, 211, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-l', '字母吊飾 L', 'Initial L', 'charm', 'gold', 65, '', '', 0, 212, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-m', '字母吊飾 M', 'Initial M', 'charm', 'gold', 65, '', '', 0, 213, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-n', '字母吊飾 N', 'Initial N', 'charm', 'gold', 65, '', '', 0, 214, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-o', '字母吊飾 O', 'Initial O', 'charm', 'gold', 65, '', '', 0, 215, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-p', '字母吊飾 P', 'Initial P', 'charm', 'gold', 65, '', '', 0, 216, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-q', '字母吊飾 Q', 'Initial Q', 'charm', 'gold', 65, '', '', 0, 217, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-r', '字母吊飾 R', 'Initial R', 'charm', 'gold', 65, '', '', 0, 218, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-s', '字母吊飾 S', 'Initial S', 'charm', 'gold', 65, '', '', 0, 219, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-t', '字母吊飾 T', 'Initial T', 'charm', 'gold', 65, '', '', 0, 220, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-u', '字母吊飾 U', 'Initial U', 'charm', 'gold', 65, '', '', 0, 221, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-v', '字母吊飾 V', 'Initial V', 'charm', 'gold', 65, '', '', 0, 222, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-w', '字母吊飾 W', 'Initial W', 'charm', 'gold', 65, '', '', 0, 223, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-x', '字母吊飾 X', 'Initial X', 'charm', 'gold', 65, '', '', 0, 224, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-y', '字母吊飾 Y', 'Initial Y', 'charm', 'gold', 65, '', '', 0, 225, 1);
INSERT OR IGNORE INTO accessories (id, zh, en, type, metal, price, note, photo, stock, sort, active) VALUES ('initial-z', '字母吊飾 Z', 'Initial Z', 'charm', 'gold', 65, '', '', 0, 226, 1);
