-- 成品規格依新的尺寸模型補齊。舊模型把「手圍」當成珠心圈，成品內圈比
-- 客人的手腕小了 π×珠徑，這 32 款因此全都串不滿真實的手圍（62–77%）
-- ——照原本的節奏補上 4–5 件後回到 92–95%，主石與吊飾不重複。
-- 前台 app/series.ts 的內建備援同步更新。

UPDATE products SET spec='rose.x,rose.l,rhodonite.l,silver-round,rose.l,moon.l,rose.l,clear.l,gold-rondelle,rose.l,garnet.l,rose.l,rose.l,rhodonite.l,silver-round,rose.l,moon.l,heart' WHERE series_id='bloom' AND id='first-love';
UPDATE products SET spec='moon.s,clear.s,moon.s,garnet.s,gold-rondelle,moon.s,aqua.s,moon.s,rose.s,gold-knot,moon.s,rhodonite.s,moon.s,clear.s,silver-flower,moon.s,garnet.s,moon.s,clear.s,moon.s,garnet.s,butterfly' WHERE series_id='bloom' AND id='soft-secret';
UPDATE products SET spec='rhodonite.x,moon.x,gold-knot,rhodonite.x,clear.x,rhodonite.x,silver-flower,garnet.x,rhodonite.x,moon.x,gold-knot,rhodonite.x' WHERE series_id='bloom' AND id='full-bloom';
UPDATE products SET spec='clear.x,clear.l,garnet.l,clear.l,silver-flower,aqua.l,clear.l,rose.l,clear.l,silver-round,rhodonite.l,clear.l,garnet.s,clear.l,garnet.l,clear.l,silver-flower,lotus' WHERE series_id='bloom' AND id='fading-words';
UPDATE products SET spec='aqua.l,clear.l,aqua.l,fluorite.l,silver-round,aqua.l,moon.l,aqua.l,moss.l,silver-star,aqua.l,amethyst.l,aqua.l,aqua.l,clear.l,aqua.l,fluorite.l,shell' WHERE series_id='serene' AND id='deep-breath';
UPDATE products SET spec='clear.s,fluorite.s,clear.s,moon.s,silver-star,clear.s,moss.s,clear.s,amethyst.s,silver-flower,clear.s,aqua.s,clear.s,fluorite.s,silver-round,clear.s,moon.s,clear.s,fluorite.s,clear.s,moon.s,moon-charm' WHERE series_id='serene' AND id='morning-clarity';
UPDATE products SET spec='amethyst.x,aqua.x,silver-flower,amethyst.x,clear.x,amethyst.x,silver-round,fluorite.x,amethyst.x,aqua.x,silver-flower,amethyst.x' WHERE series_id='serene' AND id='deep-pool';
UPDATE products SET spec='fluorite.x,fluorite.l,moon.l,fluorite.l,silver-round,moss.l,fluorite.l,amethyst.l,fluorite.l,silver-star,aqua.l,fluorite.l,moon.s,fluorite.l,moon.l,fluorite.l,silver-round,leaf' WHERE series_id='serene' AND id='breath-gradient';
UPDATE products SET spec='labradorite.x,labradorite.l,amethyst.l,silver-hex,labradorite.l,tourmaline.l,labradorite.l,moon.l,silver-round,labradorite.l,lapis.l,labradorite.l,labradorite.l,amethyst.l,silver-hex,labradorite.l,tourmaline.l,evil-eye' WHERE series_id='aurora' AND id='aurora-guard';
UPDATE products SET spec='moon.s,lapis.s,moon.s,obsidian.s,silver-round,moon.s,labradorite.s,moon.s,amethyst.s,silver-cube,moon.s,tourmaline.s,moon.s,lapis.s,silver-hex,moon.s,obsidian.s,moon.s,lapis.s,moon.s,obsidian.s,moon-charm' WHERE series_id='aurora' AND id='stardust';
UPDATE products SET spec='obsidian.x,labradorite.x,silver-cube,obsidian.x,amethyst.x,obsidian.x,silver-hex,tourmaline.x,obsidian.x,labradorite.x,silver-cube,obsidian.x' WHERE series_id='aurora' AND id='night-shield';
UPDATE products SET spec='lapis.x,lapis.l,obsidian.l,lapis.l,silver-hex,labradorite.l,lapis.l,amethyst.l,lapis.l,silver-round,tourmaline.l,lapis.l,obsidian.s,lapis.l,obsidian.l,lapis.l,silver-hex,hamsa' WHERE series_id='aurora' AND id='flowing-gradient';
UPDATE products SET spec='citrine.x,tiger.x,gold-crown,citrine.x,goldstone.x,citrine.x,gold-rondelle,sunstone.x,citrine.x,tiger.x,gold-crown,citrine.x' WHERE series_id='abundance' AND id='golden-fortune';
UPDATE products SET spec='clear.s,rose.s,clear.s,citrine.s,clear.s,gold-rondelle,tiger.s,clear.s,goldstone.s,clear.s,sunstone.s,gold-knot,clear.s,rose.s,clear.s,citrine.s,clear.s,rose.s,clear.s,citrine.s,compass' WHERE series_id='abundance' AND id='fine-gold';
UPDATE products SET spec='tiger.x,tiger.l,goldstone.l,gold-knot,tiger.l,sunstone.l,tiger.l,clear.l,gold-pixiu,tiger.l,rose.l,tiger.l,tiger.l,goldstone.l,gold-knot,tiger.l,sunstone.l,key' WHERE series_id='abundance' AND id='tiger-decision';
UPDATE products SET spec='goldstone.x,goldstone.l,sunstone.l,goldstone.l,gold-pixiu,clear.l,goldstone.l,rose.l,goldstone.l,gold-crown,citrine.l,goldstone.l,sunstone.s,goldstone.l,sunstone.l,goldstone.l,gold-pixiu,clover' WHERE series_id='abundance' AND id='rising-road';
UPDATE products SET spec='moon.s,rose.s,moon.s,clear.s,moon.s,silver-round,aqua.s,moon.s,fluorite.s,moon.s,amethyst.s,moon.s,silver-star,rose.s,moon.s,clear.s,moon.s,moon.s,rose.s,moon.s,clear.s' WHERE series_id='whisper' AND id='plain-days';
UPDATE products SET spec='aqua.s,fluorite.s,aqua.s,amethyst.s,aqua.s,silver-star,moon.s,aqua.s,rose.s,aqua.s,clear.s,silver-round,aqua.s,fluorite.s,aqua.s,amethyst.s,aqua.s,fluorite.s,aqua.s,amethyst.s,moon-charm' WHERE series_id='whisper' AND id='sea-breeze';
UPDATE products SET spec='rose.l,clear.l,rose.l,aqua.l,silver-round,rose.l,fluorite.l,rose.l,amethyst.l,silver-star,rose.l,moon.l,rose.l,rose.l,clear.l,rose.l,aqua.l,star-charm' WHERE series_id='whisper' AND id='soft-weight';
UPDATE products SET spec='amethyst.x,amethyst.l,moon.l,amethyst.l,silver-star,rose.l,amethyst.l,clear.l,amethyst.l,silver-round,aqua.l,amethyst.l,moon.s,amethyst.l,moon.l,amethyst.l,silver-star,moon-charm' WHERE series_id='whisper' AND id='two-tone';
UPDATE products SET spec='obsidian.x,obsidian.l,hematite.l,silver-hex,obsidian.l,tiger-eye.l,obsidian.l,goldstone.l,gold-hex,obsidian.l,lava.l,obsidian.l,obsidian.l,hematite.l,silver-hex,obsidian.l,tiger-eye.l,travel-compass' WHERE series_id='forge' AND id='polar-night';
UPDATE products SET spec='hematite.s,tiger-eye.s,hematite.s,goldstone.s,hematite.s,gold-hex,lava.s,hematite.s,smoky.s,hematite.s,obsidian.s,gold-pixiu,hematite.s,tiger-eye.s,hematite.s,goldstone.s,hematite.s,tiger-eye.s,hematite.s,goldstone.s,key' WHERE series_id='forge' AND id='minimal-black';
UPDATE products SET spec='lava.x,smoky.x,gold-pixiu,lava.x,obsidian.x,lava.x,silver-tiger-spacer,hematite.x,lava.x,smoky.x,gold-pixiu,lava.x' WHERE series_id='forge' AND id='lava-warrior';
UPDATE products SET spec='tiger-eye.x,tiger-eye.l,goldstone.l,tiger-eye.l,silver-tiger-spacer,lava.l,tiger-eye.l,smoky.l,tiger-eye.l,silver-hex,obsidian.l,tiger-eye.l,goldstone.s,tiger-eye.l,goldstone.l,tiger-eye.l,silver-tiger-spacer,compass' WHERE series_id='forge' AND id='tiger-market';
UPDATE products SET spec='hematite.x,obsidian.x,silver-cube,hematite.x,smoky.x,hematite.x,silver-rivet,lava.x,hematite.x,obsidian.x,silver-cube,hematite.x' WHERE series_id='bedrock' AND id='true-bedrock';
UPDATE products SET spec='smoky.l,lava.l,smoky.l,tourmaline.l,silver-rivet,smoky.l,labradorite.l,smoky.l,hematite.l,silver-groove,smoky.l,obsidian.l,smoky.l,smoky.l,lava.l,smoky.l,tourmaline.l,cross' WHERE series_id='bedrock' AND id='bedrock-daily';
UPDATE products SET spec='labradorite.x,labradorite.l,hematite.l,silver-groove,labradorite.l,obsidian.l,labradorite.l,smoky.l,silver-shield,labradorite.l,lava.l,labradorite.l,labradorite.l,hematite.l,silver-groove,labradorite.l,obsidian.l,travel-compass' WHERE series_id='bedrock' AND id='glint-in-stone';
UPDATE products SET spec='lava.x,lava.l,tourmaline.l,lava.l,silver-shield,labradorite.l,lava.l,hematite.l,lava.l,silver-cube,obsidian.l,lava.l,tourmaline.s,lava.l,tourmaline.l,lava.l,silver-shield,arrow' WHERE series_id='bedrock' AND id='strata';
UPDATE products SET spec='lapis.s,clear.s,lapis.s,tiger-eye.s,lapis.s,silver-groove,smoky.s,lapis.s,hematite.s,lapis.s,sunstone.s,lapis.s,silver-chain,clear.s,lapis.s,tiger-eye.s,lapis.s,lapis.s,clear.s,lapis.s,tiger-eye.s' WHERE series_id='velocity' AND id='fine-line';
UPDATE products SET spec='hematite.x,hematite.l,sunstone.l,silver-chain,hematite.l,lapis.l,hematite.l,clear.l,silver-hex,hematite.l,tiger-eye.l,hematite.l,hematite.l,sunstone.l,silver-chain,hematite.l,lapis.l,arrow' WHERE series_id='velocity' AND id='core-focus';
UPDATE products SET spec='clear.l,tiger-eye.l,clear.l,smoky.l,silver-hex,clear.l,hematite.l,clear.l,sunstone.l,silver-groove,clear.l,lapis.l,clear.l,clear.l,tiger-eye.l,clear.l,smoky.l,star-charm' WHERE series_id='velocity' AND id='deep-tempo';
UPDATE products SET spec='sunstone.x,sunstone.l,lapis.l,sunstone.l,silver-groove,clear.l,sunstone.l,tiger-eye.l,sunstone.l,silver-chain,smoky.l,sunstone.l,lapis.s,sunstone.l,lapis.l,sunstone.l,silver-groove,key' WHERE series_id='velocity' AND id='accel-gradient';
