#!/usr/bin/env python3
"""Derive a representative base color for every stone/accessory from its own
photo, for the WebGL 3D preview's materials.

The old hand-authored Stone.color/light/deep fields were removed as dead
code once every material had a photo (they only fed a CSS gradient
fallback that photo coverage made unreachable) — see the "Remove the dead
procedural-render fallback" commit. Re-authoring colors by hand for a new
purpose would create a second, driftable source of truth for something the
photo already encodes. Sample it instead: every material already has a
top-down, evenly-lit product photo, so its median opaque-pixel color is a
faithful stand-in for the gem's true color.

Writes app/bead-colors.ts (generated — do not hand-edit; re-run after any
photo changes affecting served materials).

    python3 scripts/derive-bead-colors.py
"""
import pathlib
import re

from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "app" / "bead-colors.ts"


def median_color(path: pathlib.Path) -> str:
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    px = im.load()
    rs, gs, bs = [], [], []
    for y in range(0, h, 2):
        for x in range(0, w, 2):
            r, g, b, a = px[x, y]
            if a > 200:
                rs.append(r); gs.append(g); bs.append(b)
    if not rs:
        return "#999999"
    rs.sort(); gs.sort(); bs.sort()
    n = len(rs)
    r, g, b = rs[n // 2], gs[n // 2], bs[n // 2]
    return f"#{r:02x}{g:02x}{b:02x}"


def main() -> None:
    src = (ROOT / "app" / "catalog.tsx").read_text(encoding="utf-8")

    def parse_map(name: str) -> dict:
        m = re.search(rf'export const {name}: Record<string, string> = \{{(.*?)\n\}};', src, re.S)
        body = m.group(1)
        # Each row is either `id: "/path"` or `"hyphen-id": "/path"`.
        return {
            (quoted or bare): path
            for quoted, bare, path in re.findall(r'(?:"([\w-]+)"|(\b[a-zA-Z][\w-]*\b)):\s*"([^"]+)"', body)
        }

    stone_photos = parse_map("stonePhotos")
    accessory_photos = parse_map("accessoryPhotos")

    lines = [
        "// AUTO-GENERATED by scripts/derive-bead-colors.py — do not hand-edit.",
        "// Median opaque-pixel color sampled from each material's own product photo,",
        "// used as the base color for the WebGL 3D preview's PBR materials.",
        "export const STONE_COLORS: Record<string, string> = {",
    ]
    for stone_id, rel in sorted(stone_photos.items()):
        color = median_color(ROOT / "public" / rel.lstrip("/"))
        lines.append(f'  "{stone_id}": "{color}",')
    lines.append("};")
    lines.append("export const ACCESSORY_COLORS: Record<string, string> = {")
    for acc_id, rel in sorted(accessory_photos.items()):
        color = median_color(ROOT / "public" / rel.lstrip("/"))
        lines.append(f'  "{acc_id}": "{color}",')
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(stone_photos)} stones, {len(accessory_photos)} accessories)")


if __name__ == "__main__":
    main()
