#!/usr/bin/env python3
"""從素材照片自動推導「這個零件怎麼掛在繩子上」。

一張去背的配件照裡，穿繩用的孔是一塊「不與圖片邊界相連的透明區域」——
隔珠是正中央的大洞，吊飾是頂端扣環的小洞，圓珠則完全沒有洞（頂視圖看
不到鑽孔）。用 alpha 通道把這種封閉孔洞找出來，就能自動得到：

    aspect       實際圖案的長寬比（圖檔四周的留白已排除）
    box          圖案在圖檔中的範圍 [x0,y0,x1,y1]（圖檔寬高的比例）——
                 渲染時要靠它把圖放大裁切，讓圖案剛好填滿顯示框，
                 否則 object-fit:contain 會把整張含留白的圖縮進去，
                 細長的吊飾就只剩中間一小條
    holeTop      最靠上的孔（吊飾的扣環）在圖案內的相對座標 [0,1]
    holeCentral  中央的大孔（隔珠的穿繩孔）在圖案內的相對座標 [0,1]

「這是圓珠還是吊飾」由素材自己的類型決定（那是人工建檔的權威資料），
照片只負責它擅長的部分：量出輪廓比例與孔在哪。渲染時把對應的孔對準
繩子，配件才不會浮在旁邊或歪掉。

用法：python3 scripts/derive-piece-shapes.py  → 覆寫 app/piece-shapes.ts
"""
import json
import pathlib
import sys

import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = pathlib.Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
OUT = ROOT / "app" / "piece-shapes.ts"
# looks/ 是成品實景照、textures/ 是 3D 貼圖，兩者都不是零件
SKIP_DIRS = {"looks", "textures", "banners", "video", "brand", "fonts"}
ALPHA_THRESHOLD = 40
MIN_HOLE_PX = 12


def analyse(path: pathlib.Path):
    im = Image.open(path).convert("RGBA")
    alpha = np.array(im.getchannel("A"))
    solid = alpha >= ALPHA_THRESHOLD
    if not solid.any():
        return None
    ys, xs = np.nonzero(solid)
    y0, y1, x0, x1 = ys.min(), ys.max() + 1, xs.min(), xs.max() + 1
    bw, bh = x1 - x0, y1 - y0
    if bw < 4 or bh < 4:
        return None
    aspect = float(bw) / float(bh)

    # 透明區域分群；碰到圖片邊界的那些是背景，剩下的才是真正的孔
    holes_lbl, n = ndimage.label(~solid)
    border = set(holes_lbl[0, :]) | set(holes_lbl[-1, :]) | set(holes_lbl[:, 0]) | set(holes_lbl[:, -1])
    border.discard(0)
    enclosed = []
    for lab in range(1, n + 1):
        if lab in border:
            continue
        mask = holes_lbl == lab
        area = int(mask.sum())
        if area < MIN_HOLE_PX:
            continue
        hy, hx = np.nonzero(mask)
        enclosed.append({"area": area, "top": int(hy.min()), "cx": float(hx.mean()), "cy": float(hy.mean())})

    body_area = int(solid.sum())
    rel = lambda h: [round((h["cx"] - x0) / bw, 4), round((h["cy"] - y0) / bh, 4)]
    H, W = solid.shape
    out = {
        "aspect": round(aspect, 3),
        "box": [round(x0 / W, 4), round(y0 / H, 4), round(x1 / W, 4), round(y1 / H, 4)],
        "holeTop": None,
        "holeCentral": None,
    }
    if not enclosed:
        return out                                  # 沒有孔（圓珠的頂視圖看不到鑽孔）

    # 最靠上的孔＝吊飾的扣環。落在下半部的多半是鏤空裝飾，不是穿繩處。
    enclosed.sort(key=lambda h: h["top"])
    top = enclosed[0]
    if (top["cy"] - y0) / bh < 0.45:
        out["holeTop"] = rel(top)

    # 夠大、又夠靠近中心的孔＝隔珠的穿繩孔
    biggest = max(enclosed, key=lambda h: h["area"])
    if (biggest["area"] > body_area * 0.06
            and abs((biggest["cx"] - x0) / bw - 0.5) < 0.22
            and abs((biggest["cy"] - y0) / bh - 0.5) < 0.22):
        out["holeCentral"] = rel(biggest)
    return out


def main() -> None:
    shapes: dict[str, dict] = {}
    counts: dict[str, int] = {}
    files = sorted(
        p for p in PUBLIC.rglob("*.png")
        if not SKIP_DIRS & set(p.relative_to(PUBLIC).parts[:-1])
    )
    for path in files:
        try:
            r = analyse(path)
        except Exception as exc:                       # noqa: BLE001 — 壞圖不該整批中斷
            print(f"  ! {path.name}: {exc}", file=sys.stderr)
            continue
        if not r:
            continue
        key = "/" + str(path.relative_to(PUBLIC)).replace("\\", "/")
        shapes[key] = r
        kind = "central" if r["holeCentral"] else "top" if r["holeTop"] else "solid"
        counts[kind] = counts.get(kind, 0) + 1

    def fmt(v):
        b = v["box"]
        parts = [f'aspect: {v["aspect"]}', f'box: [{b[0]}, {b[1]}, {b[2]}, {b[3]}]']
        if v["holeTop"]:
            parts.append(f'holeTop: [{v["holeTop"][0]}, {v["holeTop"][1]}]')
        if v["holeCentral"]:
            parts.append(f'holeCentral: [{v["holeCentral"][0]}, {v["holeCentral"][1]}]')
        return "{ " + ", ".join(parts) + " }"

    body = ",\n".join(f'  "{k}": {fmt(v)}' for k, v in sorted(shapes.items()))
    OUT.write_text(
        "// GENERATED by scripts/derive-piece-shapes.py — 不要手改。\n"
        "// 每個零件「怎麼掛在繩子上」：穿繩孔的位置是從去背照片的 alpha\n"
        "// 通道自動偵測出來的（不與邊界相連的透明區域就是孔）。渲染時把這\n"
        "// 個孔對準繩子，配件才不會浮在旁邊或歪掉。\n"
        "//\n"
        "// 重新產生：python3 scripts/derive-piece-shapes.py\n"
        "export type PieceShape = {\n"
        "  /** 圖案本身的寬/高（圖檔四周的留白已排除）。 */\n"
        "  aspect: number;\n"
        "  /** 圖案在圖檔裡的範圍 [x0,y0,x1,y1]，用來裁掉留白。 */\n"
        "  box: [number, number, number, number];\n"
        "  /** 最靠上的孔＝吊飾扣環，繩子從這裡穿過。 */\n"
        "  holeTop?: [number, number];\n"
        "  /** 中央的大孔＝隔珠穿繩孔。 */\n"
        "  holeCentral?: [number, number];\n"
        "};\n\n"
        "export const PIECE_SHAPES: Record<string, PieceShape> = {\n" + body + ",\n};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(shapes)} pieces  {json.dumps(counts, ensure_ascii=False)}")


if __name__ == "__main__":
    main()
